Repository swyp-mema/mema-server, pull requests merged in 2024-12, with the labels that each got.

#11 [#10] mema-server 공인 IP 변경됨에 따라 application.yml 수정
  src/main/java/com/swyp/mema/domain/meetMember/repository/MeetMemberCustomRepositoryImpl.java
  src/main/java/com/swyp/mema/domain/user/model/User.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 🐞 Bug

#13 [#12] Spring boot Swagger 3.0 적용 및 GlobalExceptionHandler 생성
  build.gradle
  src/main/java/com/swyp/mema/domain/meet/controller/MeetController.java
  src/main/java/com/swyp/mema/domain/meet/converter/MeetConverter.java
  src/main/java/com/swyp/mema/domain/meet/dto/request/CreateMeetReq.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/CreateMeetRes.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/CreateMeetResponse.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/MeetSingleRes.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/MeetSingleResponse.java
  src/main/java/com/swyp/mema/domain/meet/exception/MeetNotFoundException.java
  src/main/java/com/swyp/mema/domain/meet/service/MeetService.java
  src/main/java/com/swyp/mema/domain/meetMember/repository/MeetMemberCustomRepository.java
  src/main/java/com/swyp/mema/domain/meetMember/repository/MeetMemberCustomRepositoryImpl.java
  src/main/java/com/swyp/mema/domain/meetMember/service/MeetMemberService.java
  src/main/java/com/swyp/mema/domain/user/dto/reseponse/UserRes.java
  src/main/java/com/swyp/mema/domain/user/dto/reseponse/UserResponse.java
  src/main/java/com/swyp/mema/global/base/exception/ErrorCode.java
  src/main/java/com/swyp/mema/global/base/exception/GlobalExceptionHandler.java
  src/main/java/com/swyp/mema/global/base/exception/ServiceException.java
  src/main/java/com/swyp/mema/global/config/SwaggerConfig.java
Labels: ✨ Feature

#15 [#14] 약속 수정 및 삭제 API
  src/main/java/com/swyp/mema/domain/meet/controller/MeetController.java
  src/main/java/com/swyp/mema/domain/meet/converter/MeetConverter.java
  src/main/java/com/swyp/mema/domain/meet/dto/request/MeetNameReq.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/MeetSingleRes.java
  src/main/java/com/swyp/mema/domain/meet/exception/MeetNotFoundException.java
  src/main/java/com/swyp/mema/domain/meet/model/Meet.java
  src/main/java/com/swyp/mema/domain/meet/service/MeetService.java
  src/main/java/com/swyp/mema/domain/meetMember/converter/MeetMemberConverter.java
  src/main/java/com/swyp/mema/domain/meetMember/model/MeetMember.java
  src/main/java/com/swyp/mema/domain/meetMember/repository/MeetMemberCustomRepositoryImpl.java
  src/main/java/com/swyp/mema/domain/user/dto/reseponse/UserRes.java
Labels: ✨ Feature

#16 [#5] 커스텀 로그인 및 소셜 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/swyp/mema/MemaApplication.java
  src/main/java/com/swyp/mema/domain/meet/controller/MeetController.java
  src/main/java/com/swyp/mema/domain/meet/service/MeetService.java
  src/main/java/com/swyp/mema/domain/user/controller/JoinController.java
  src/main/java/com/swyp/mema/domain/user/controller/UserController.java
  src/main/java/com/swyp/mema/domain/user/converter/UserConverter.java
  src/main/java/com/swyp/mema/domain/user/dto/CustomOAuthUser.java
  src/main/java/com/swyp/mema/domain/user/dto/CustomUserDetails.java
  src/main/java/com/swyp/mema/domain/user/dto/request/UserReq.java
  src/main/java/com/swyp/mema/domain/user/dto/reseponse/UserRes.java
  src/main/java/com/swyp/mema/domain/user/dto/reseponse/oauth2/NaverResponse.java
  src/main/java/com/swyp/mema/domain/user/dto/reseponse/oauth2/OAuthResponse.java
  src/main/java/com/swyp/mema/domain/user/exception/EmailAlreadyExistException.java
  src/main/java/com/swyp/mema/domain/user/model/User.java
  src/main/java/com/swyp/mema/domain/user/repository/UserRepository.java
  src/main/java/com/swyp/mema/domain/user/service/CustomOAuthUserService.java
  src/main/java/com/swyp/mema/domain/user/service/CustomUserDetailsService.java
  src/main/java/com/swyp/mema/domain/user/service/JoinService.java
  src/main/java/com/swyp/mema/global/base/exception/ErrorCode.java
  src/main/java/com/swyp/mema/global/config/env/EnvConfig.java
  src/main/java/com/swyp/mema/global/config/env/EnvLoader.java
  src/main/java/com/swyp/mema/global/config/security/CorsMvcConfig.java
  src/main/java/com/swyp/mema/global/config/security/SecurityConfig.java
  src/main/java/com/swyp/mema/global/security/jwt/filter/JWTFilter.java
  src/main/java/com/swyp/mema/global/security/jwt/filter/JWTLoginFilter.java
  src/main/java/com/swyp/mema/global/security/jwt/util/JWTUtil.java
  src/main/java/com/swyp/mema/global/security/oauth2/filter/JWTFilterOAuth.java
  src/main/java/com/swyp/mema/global/security/oauth2/util/CustomSuccessHandlerCookie.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#18 [#17] My page 내 정보 조회, 수정 API 구현
  build.gradle
  src/main/java/com/swyp/mema/domain/badge/service/BadgeService.java
  src/main/java/com/swyp/mema/domain/meet/converter/MeetConverter.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/MeetSingleRes.java
  src/main/java/com/swyp/mema/domain/meet/exception/MeetNotFoundException.java
  src/main/java/com/swyp/mema/domain/meet/service/MeetService.java
  src/main/java/com/swyp/mema/domain/meetMember/repository/MeetMemberCustomRepository.java
  src/main/java/com/swyp/mema/domain/meetMember/repository/MeetMemberCustomRepositoryImpl.java
  src/main/java/com/swyp/mema/domain/meetMember/service/MeetMemberService.java
  src/main/java/com/swyp/mema/domain/user/controller/UserController.java
  src/main/java/com/swyp/mema/domain/user/dto/CustomUserDetails.java
  src/main/java/com/swyp/mema/domain/user/dto/converter/UserConverter.java
  src/main/java/com/swyp/mema/domain/user/dto/converter/UserDtoConverter.java
  src/main/java/com/swyp/mema/domain/user/dto/request/UpdateUserInfoReq.java
  src/main/java/com/swyp/mema/domain/user/dto/request/UserReq.java
  src/main/java/com/swyp/mema/domain/user/dto/response/UserInfoRes.java
  src/main/java/com/swyp/mema/domain/user/dto/response/UserRes.java
  src/main/java/com/swyp/mema/domain/user/exception/UserNotFoundException.java
  src/main/java/com/swyp/mema/domain/user/model/User.java
  src/main/java/com/swyp/mema/domain/user/service/CustomOAuthUserService.java
  src/main/java/com/swyp/mema/domain/user/service/JoinService.java
  src/main/java/com/swyp/mema/domain/user/service/UserService.java
  src/main/java/com/swyp/mema/global/base/domain/BaseEntity.java
  src/main/java/com/swyp/mema/global/base/exception/ErrorCode.java
  src/main/java/com/swyp/mema/global/security/jwt/util/JWTUtil.java
  src/main/resources/application.yml
Labels: ✨ Feature

#26 [#24] swagger 개발 서버 적용 Config 수정
  src/main/java/com/swyp/mema/global/config/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🐞 Bug

#30 [#29] Swagger CORS 이슈 해결
  src/main/java/com/swyp/mema/domain/user/controller/JoinController.java
  src/main/java/com/swyp/mema/domain/user/controller/UserController.java
  src/main/java/com/swyp/mema/domain/user/dto/response/oauth2/NaverResponse.java
  src/main/java/com/swyp/mema/domain/user/dto/response/oauth2/OAuthResponse.java
  src/main/java/com/swyp/mema/domain/user/service/CustomOAuthUserService.java
  src/main/java/com/swyp/mema/global/config/SwaggerConfig.java
  src/main/java/com/swyp/mema/global/config/security/CorsMvcConfig.java
Labels: 🐞 Bug

#28 [#27] 커스텀 로그인 컨트롤러 구현
  src/main/java/com/swyp/mema/domain/charge/converter/ChargeConverter.java
  src/main/java/com/swyp/mema/domain/user/controller/JoinController.java
  src/main/java/com/swyp/mema/domain/user/controller/UserController.java
  src/main/java/com/swyp/mema/domain/user/converter/UserConverter.java
  src/main/java/com/swyp/mema/domain/user/dto/request/JoinReq.java
  src/main/java/com/swyp/mema/domain/user/dto/request/LoginReq.java
  src/main/java/com/swyp/mema/domain/user/service/JoinService.java
  src/main/resources/application.yml
Labels: 🔧 Fix

#31 [#27] cors 관련 설정 수정
  src/main/java/com/swyp/mema/domain/user/controller/UserController.java
  src/main/java/com/swyp/mema/global/config/security/CorsMvcConfig.java
Labels: 🔧 Fix

#36 [#35] 뱃지 관련 수정
  src/main/java/com/swyp/mema/domain/user/converter/UserConverter.java
  src/main/java/com/swyp/mema/domain/user/dto/converter/UserConverter.java
  src/main/java/com/swyp/mema/domain/user/dto/converter/UserDtoConverter.java
  src/main/java/com/swyp/mema/domain/user/dto/request/UpdateUserInfoReq.java
  src/main/java/com/swyp/mema/domain/user/dto/request/UserReq.java
  src/main/java/com/swyp/mema/domain/user/dto/response/UserInfoRes.java
  src/main/java/com/swyp/mema/domain/user/dto/response/UserRes.java
  src/main/java/com/swyp/mema/domain/user/model/User.java
  src/main/java/com/swyp/mema/domain/user/service/CustomOAuthUserService.java
  src/main/java/com/swyp/mema/domain/user/service/JoinService.java
  src/main/java/com/swyp/mema/domain/user/service/UserService.java
Labels: 🔧 Fix

#33 [#32] 지하철 정보 조회를 위한 OpenAPI 통신
  build.gradle
  src/main/java/com/swyp/mema/domain/charge/controller/ChargeController.java
  src/main/java/com/swyp/mema/domain/meet/controller/MeetController.java
  src/main/java/com/swyp/mema/domain/meet/converter/MeetConverter.java
  src/main/java/com/swyp/mema/domain/meet/dto/request/MeetNameReq.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/MeetHomeDetailResponse.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/MeetHomeResponse.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/SingleMeetRes.java
  src/main/java/com/swyp/mema/domain/meet/exception/MaxActiveMeetsExceededException.java
  src/main/java/com/swyp/mema/domain/meet/exception/MeetNameOverLengthException.java
  src/main/java/com/swyp/mema/domain/meet/exception/NotEmptyMeetNameException.java
  src/main/java/com/swyp/mema/domain/meet/model/Meet.java
  src/main/java/com/swyp/mema/domain/meet/model/vo/State.java
  src/main/java/com/swyp/mema/domain/meet/repository/MeetCustomRepository.java
  src/main/java/com/swyp/mema/domain/meet/repository/MeetCustomRepositoryImpl.java
  src/main/java/com/swyp/mema/domain/meet/repository/MeetRepository.java
  src/main/java/com/swyp/mema/domain/meet/service/MeetService.java
  src/main/java/com/swyp/mema/domain/meetMember/dto/response/MeetMemberRes.java
  src/main/java/com/swyp/mema/domain/meetMember/repository/MeetMemberCustomRepository.java
  src/main/java/com/swyp/mema/domain/meetMember/repository/MeetMemberCustomRepositoryImpl.java
  src/main/java/com/swyp/mema/domain/meetMember/repository/MeetMemberRepository.java
  src/main/java/com/swyp/mema/domain/meetMember/service/MeetMemberService.java
  src/main/java/com/swyp/mema/domain/station/controller/StationController.java
  src/main/java/com/swyp/mema/domain/station/converter/StationConverter.java
  src/main/java/com/swyp/mema/domain/station/dto/response/OpenApiBasicResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/SingleStationResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/TotalStationResponse.java
  src/main/java/com/swyp/mema/domain/station/model/Station.java
  src/main/java/com/swyp/mema/domain/station/repository/StationRepository.java
  src/main/java/com/swyp/mema/domain/station/service/StationService.java
  src/main/java/com/swyp/mema/domain/user/controller/JoinController.java
  src/main/java/com/swyp/mema/domain/user/dto/response/UserRes.java
  src/main/java/com/swyp/mema/domain/voteDate/controller/VoteDateController.java
  src/main/java/com/swyp/mema/domain/voteDate/exception/InvalidFinalVoteDateException.java
  src/main/java/com/swyp/mema/domain/voteDate/exception/UnsatisfactoryFinalDateException.java
  src/main/java/com/swyp/mema/domain/voteDate/model/VoteDate.java
  src/main/java/com/swyp/mema/domain/voteDate/repository/VoteDateCustomRepository.java
  src/main/java/com/swyp/mema/domain/voteDate/repository/VoteDateCustomRepositoryImpl.java
  src/main/java/com/swyp/mema/domain/voteDate/service/VoteDateService.java
  src/main/java/com/swyp/mema/domain/voteLocation/controller/LocationController.java
  src/main/java/com/swyp/mema/domain/voteLocation/converter/LocationConverter.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/request/CreateLocationReq.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/response/SingleLocationResponse.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/response/TotalLocationResponse.java
  src/main/java/com/swyp/mema/domain/voteLocation/exception/LocationNotFoundException.java
  src/main/java/com/swyp/mema/domain/voteLocation/model/Location.java
  src/main/java/com/swyp/mema/domain/voteLocation/repository/LocationRepository.java
  src/main/java/com/swyp/mema/domain/voteLocation/service/LocationService.java
  src/main/java/com/swyp/mema/global/base/domain/BaseEntity.java
  src/main/java/com/swyp/mema/global/base/exception/ErrorCode.java
  src/main/java/com/swyp/mema/global/config/ApiConfig.java
  src/main/java/com/swyp/mema/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature

#44 [#43] 정산 API 응답 수정, 일정투표 삭제기능 추가
  src/main/java/com/swyp/mema/domain/charge/converter/ChargeConverter.java
  src/main/java/com/swyp/mema/domain/charge/dto/request/ChargeReq.java
  src/main/java/com/swyp/mema/domain/charge/dto/response/ChargeRes.java
  src/main/java/com/swyp/mema/domain/charge/dto/response/PayerInfo.java
  src/main/java/com/swyp/mema/domain/charge/model/ChargeMember.java
  src/main/java/com/swyp/mema/domain/voteDate/controller/VoteDateController.java
  src/main/java/com/swyp/mema/domain/voteDate/service/VoteDateService.java
Labels: 🔧 Fix

#48 [#47] OpenAPI 통해 중간거리구현을 위한 지하철역 정보 데이터 바인딩 완료
  src/main/java/com/swyp/mema/domain/station/controller/StationController.java
  src/main/java/com/swyp/mema/domain/station/converter/StationConverter.java
  src/main/java/com/swyp/mema/domain/station/dto/response/nearSubway/NearSubwayBasicResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/nearSubway/NearSubwayResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/nearSubway/TotalNearSubwayResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayInfo/SingleStationResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayInfo/SubwayInfoBasicResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayInfo/TotalStationResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayMaster/SubwayMasterBasicResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayMaster/SubwayMasterResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayMaster/TotalSubwayMasterResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayTime/SubwayTimeBasicResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayTime/SubwayTimeResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayTime/TotalSubwayTimeResponse.java
  src/main/java/com/swyp/mema/domain/station/model/Station.java
  src/main/java/com/swyp/mema/domain/station/service/NearStationService.java
  src/main/java/com/swyp/mema/domain/station/service/StationMasterService.java
  src/main/java/com/swyp/mema/domain/station/service/StationService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#49 [#47] API key 값 이름 변경
  src/main/resources/application.yml
Labels: 🔧 Fix

#50 hot-fix : roll back VoteDateService
  src/main/java/com/swyp/mema/domain/voteDate/service/VoteDateService.java
Labels: 🔧 Fix

#52 [#41] Station ERD 수정 및 지하철역 조회 시 위도&경도 뱉도록 수정
  src/main/java/com/swyp/mema/domain/station/controller/StationController.java
  src/main/java/com/swyp/mema/domain/station/converter/StationConverter.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayInfo/SingleStationResponse.java
  src/main/java/com/swyp/mema/domain/station/exception/StationNotFoundException.java
  src/main/java/com/swyp/mema/domain/station/model/Station.java
  src/main/java/com/swyp/mema/domain/station/service/StationMasterService.java
  src/main/java/com/swyp/mema/domain/station/service/StationService.java
  src/main/java/com/swyp/mema/global/base/exception/ErrorCode.java
Labels: 🔧 Fix

#53 [#41] /meets/home 검증 추가
  src/main/java/com/swyp/mema/domain/meet/service/MeetService.java
  src/main/java/com/swyp/mema/global/base/exception/ErrorCode.java
Labels: 🔧 Fix

#54 [#41] 위도&경도 동일한 값 세팅으로 인한 에러 해결
  src/main/java/com/swyp/mema/domain/station/controller/StationController.java
  src/main/java/com/swyp/mema/domain/station/service/StationMasterService.java
  src/main/java/com/swyp/mema/domain/voteLocation/converter/LocationConverter.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/request/CreateLocationReq.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/response/SingleLocationResponse.java
  src/main/java/com/swyp/mema/domain/voteLocation/model/Location.java
Labels: 🔧 Fix

#58 [#57] Internal server error 에러 해결을 위한 기본 루트 설정
  src/main/java/com/swyp/mema/global/base/api/BaseController.java
Labels: 🌎 Deploy

#59 [#60] 중간역 조회 API 구현
  build.gradle
  src/main/java/com/swyp/mema/domain/midloc/service/MidLocService.java
  src/main/java/com/swyp/mema/domain/midloc/service/OpenAIWorker.java
  src/main/java/com/swyp/mema/domain/midloc/service/Stations.java
  src/main/java/com/swyp/mema/domain/midloc/service/structures/NextStation.java
  src/main/java/com/swyp/mema/domain/midloc/service/structures/StationInfo.java
  src/main/java/com/swyp/mema/domain/midloc/service/structures/TransferStation.java
  src/main/java/com/swyp/mema/domain/midloc/service/structures/UserInfo.java
  src/main/java/com/swyp/mema/domain/station/converter/StationConverter.java
  src/main/java/com/swyp/mema/domain/station/dto/response/nearSubway/NearSubwayBasicResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/nearSubway/NearSubwayResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayMaster/SubwayMasterBasicResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayMaster/SubwayMasterResponse.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayTime/SubwayTimeResponse.java
  src/main/java/com/swyp/mema/domain/station/service/NearStationService.java
  src/main/java/com/swyp/mema/domain/station/service/StationMasterService.java
  src/main/java/com/swyp/mema/domain/voteLocation/controller/LocationController.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/response/MidLocationResponse.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/response/TotalLocationResponse.java
  src/main/java/com/swyp/mema/domain/voteLocation/service/LocationService.java
  src/main/java/com/swyp/mema/global/config/env/EnvConfig.java
Labels: ✨ Feature

#61 chore: cors origin 업데이트
  src/main/java/com/swyp/mema/global/config/security/CorsMvcConfig.java
  src/main/java/com/swyp/mema/global/config/security/SecurityConfig.java
Labels: 🔧 Fix

#62 [#60] 위치 전체 조회 시 유저 Response 타입 반환
  src/main/java/com/swyp/mema/domain/midloc/service/MidLocService.java
  src/main/java/com/swyp/mema/global/base/api/BaseController.java
Labels: 🔧 Fix

#64 [#63] 일정 투표 API 수정
  src/main/java/com/swyp/mema/domain/meet/dto/response/SingleMeetRes.java
  src/main/java/com/swyp/mema/domain/meet/model/Meet.java
  src/main/java/com/swyp/mema/domain/midloc/service/MidLocService.java
  src/main/java/com/swyp/mema/domain/voteDate/controller/VoteDateController.java
  src/main/java/com/swyp/mema/domain/voteDate/dto/request/CreateVoteDateReq.java
  src/main/java/com/swyp/mema/domain/voteDate/service/VoteDateService.java
Labels: 🛠️ Refactor

#66 [#65] 역 DB 중복 이슈 & Chat GPT 호출 시점 변경 및 중간 지점 값이 변경되는 이슈 해결
  src/main/java/com/swyp/mema/domain/meet/converter/MeetConverter.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/SingleMeetRes.java
  src/main/java/com/swyp/mema/domain/meet/model/Meet.java
  src/main/java/com/swyp/mema/domain/meetMember/model/MeetMember.java
  src/main/java/com/swyp/mema/domain/midloc/service/MidLocService.java
  src/main/java/com/swyp/mema/domain/midloc/service/Stations.java
  src/main/java/com/swyp/mema/domain/station/controller/StationController.java
  src/main/java/com/swyp/mema/domain/station/service/StationService.java
  src/main/java/com/swyp/mema/domain/voteLocation/controller/LocationController.java
  src/main/java/com/swyp/mema/domain/voteLocation/exception/DuplicateVoteException.java
  src/main/java/com/swyp/mema/domain/voteLocation/exception/OnlyOneVoteException.java
  src/main/java/com/swyp/mema/domain/voteLocation/service/LocationService.java
  src/main/java/com/swyp/mema/global/base/exception/ErrorCode.java
Labels: 🐞 Bug, 🔧 Fix

#68 [#41] 일정 /home Response 수정 및 Post 요청 시 검증 추가
  src/main/java/com/swyp/mema/domain/meet/converter/MeetConverter.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/MeetHomeDetailRes.java
  src/main/java/com/swyp/mema/domain/meet/service/MeetService.java
  src/main/java/com/swyp/mema/domain/meetMember/dto/response/MeetMemberRes.java
  src/main/java/com/swyp/mema/domain/meetMember/model/MeetMember.java
  src/main/java/com/swyp/mema/domain/voteDate/exception/DuplicateDateVoteException.java
  src/main/java/com/swyp/mema/domain/voteDate/service/VoteDateService.java
  src/main/java/com/swyp/mema/domain/voteLocation/exception/DuplicateLocationVoteException.java
  src/main/java/com/swyp/mema/domain/voteLocation/service/LocationService.java
  src/main/java/com/swyp/mema/global/base/exception/ErrorCode.java
Labels: 🔧 Fix

#72 [#71] @Builder @AllArgsConstructor 중복 사용으로 인한 QueryDSL 에러
  src/main/java/com/swyp/mema/domain/meet/converter/MeetConverter.java
  src/main/java/com/swyp/mema/domain/meetMember/dto/response/MeetMemberRes.java
  src/main/java/com/swyp/mema/domain/user/dto/response/UserRes.java
  src/main/java/com/swyp/mema/domain/user/model/User.java
Labels: 🔧 Fix

#82 hot-fix: 미팅 생성시 뱃지 로직 수정
  src/main/java/com/swyp/mema/domain/meet/service/MeetService.java
Labels: 🔧 Fix

#86 [#41] 프론트 로컬 서버 CORS 이슈 해결
  src/main/java/com/swyp/mema/global/config/security/CorsMvcConfig.java
Labels: 🔧 Fix

#87 [#41] 프론트 로컬 서버 CORS 이슈 해결
  src/main/java/com/swyp/mema/global/config/security/SecurityConfig.java
Labels: 🐞 Bug
