Repository swyp-mema/mema-server, pull requests merged in 2025-02, with the labels that each got.

#92 AWS EC2 env 파일 수정 및 jenkins CI/CD 구축 테스트
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🌎 Deploy

#94 Spring Security & CorsMvcConfig CORS 설정 중복으로 인한 미적용
  src/main/java/com/swyp/mema/domain/charge/controller/ChargeController.java
  src/main/java/com/swyp/mema/domain/charge/converter/ChargeConverter.java
  src/main/java/com/swyp/mema/domain/charge/service/ChargeService.java
  src/main/java/com/swyp/mema/domain/user/service/CustomOAuthUserService.java
  src/main/java/com/swyp/mema/domain/user/service/EmailAuthServiceCustom.java
  src/main/java/com/swyp/mema/global/config/security/CorsMvcConfig.java
  src/main/java/com/swyp/mema/global/config/security/SecurityConfig.java
  src/main/java/com/swyp/mema/global/security/filter/jwt/JWTFilter.java
  src/main/java/com/swyp/mema/global/security/filter/jwt/JWTLoginFilter.java
  src/main/java/com/swyp/mema/global/security/filter/oauth2/JWTFilterOAuth.java
  src/main/java/com/swyp/mema/global/security/util/jwt/JWTUtil.java
  src/main/java/com/swyp/mema/global/security/util/oauth2/CustomSuccessHandlerCookie.java
Labels: ⚙️ Setting, 🌎 Deploy

#89 [#88] Naver OpenAPI 가게 추천 및 가게 이미지 크롤링 기능 추가
  build.gradle
  src/main/java/com/swyp/mema/domain/store/converter/StoreConverter.java
  src/main/java/com/swyp/mema/domain/store/dto/BasicStoreRes.java
  src/main/java/com/swyp/mema/domain/store/dto/ImageRes.java
  src/main/java/com/swyp/mema/domain/store/dto/StoreRes.java
  src/main/java/com/swyp/mema/domain/store/dto/TotalStoreRes.java
  src/main/java/com/swyp/mema/domain/store/service/NaverMapCrawler.java
  src/main/java/com/swyp/mema/domain/store/service/NaverStoreSearchService.java
  src/main/java/com/swyp/mema/domain/store/service/StoreService.java
  src/main/java/com/swyp/mema/domain/voteLocation/controller/LocationController.java
  src/main/java/com/swyp/mema/domain/voteLocation/service/LocationService.java
  src/main/java/com/swyp/mema/global/base/exception/GlobalExceptionHandler.java
Labels: ✨ Feature

#98 CORS 에러 Nginx Config 및 Spring SecurityConifg 변경
  src/main/java/com/swyp/mema/global/config/security/SecurityConfig.java
Labels: ⚙️ Setting

#96 [#95] database 패키지 구조 생성
  src/main/java/com/swyp/mema/database/openapi/location/converter/StationConverter.java
  src/main/java/com/swyp/mema/database/openapi/location/logic/StationMasterService.java
  src/main/java/com/swyp/mema/database/openapi/location/response/SubwayMasterBasicResponse.java
  src/main/java/com/swyp/mema/database/openapi/location/response/SubwayMasterResponse.java
  src/main/java/com/swyp/mema/database/openapi/location/response/TotalSubwayMasterResponse.java
  src/main/java/com/swyp/mema/database/station/logic/TotalDataBuilder.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/NextStationBuilder.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/RouteBuilder.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/StationDataBuilder.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/TransferStationBuilder.java
  src/main/java/com/swyp/mema/domain/station/controller/StationController.java
  src/main/java/com/swyp/mema/domain/station/service/NearStationService.java
  src/main/java/com/swyp/mema/domain/station/service/StationService.java
Labels: 🛠️ Refactor

#101 [#93] Spring Security 설정 추가하여 CORS 에러 해결
  src/main/java/com/swyp/mema/global/config/security/SecurityConfig.java
Labels: 🐞 Bug

#103 [#93] 프론트 테스트 서버 설정 추가 및 이미지 크롤링 롤백
  build.gradle
  src/main/java/com/swyp/mema/domain/store/converter/StoreConverter.java
  src/main/java/com/swyp/mema/domain/store/dto/BasicStoreRes.java
  src/main/java/com/swyp/mema/domain/store/dto/ImageRes.java
  src/main/java/com/swyp/mema/domain/store/dto/StoreRes.java
  src/main/java/com/swyp/mema/domain/store/dto/TotalStoreRes.java
  src/main/java/com/swyp/mema/domain/store/service/NaverMapCrawler.java
  src/main/java/com/swyp/mema/domain/store/service/NaverStoreSearchService.java
  src/main/java/com/swyp/mema/domain/store/service/StoreService.java
  src/main/java/com/swyp/mema/domain/voteLocation/controller/LocationController.java
  src/main/java/com/swyp/mema/domain/voteLocation/service/LocationService.java
  src/main/java/com/swyp/mema/global/base/exception/GlobalExceptionHandler.java
  src/main/java/com/swyp/mema/global/config/security/SecurityConfig.java
Labels: 🔥 Front

#100 [#97] 지하철 역 DB - Station, Route, NextStation 구축 로직 구현
  src/main/java/com/swyp/mema/database/station/controller/DBController.java
  src/main/java/com/swyp/mema/database/station/logic/ControllStationDataService.java
  src/main/java/com/swyp/mema/database/station/logic/TotalDataBuilder.java
  src/main/java/com/swyp/mema/database/station/logic/TotalDataBuilderService.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/NextStationBuilder.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/NextStationBuilderService.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/RouteBuilder.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/RouteBuilderService.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/StationDataBuilder.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/StationDataBuilderService.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/TimeInfoService.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/TransferStationBuilder.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/TransferStationBuilderService.java
  src/main/java/com/swyp/mema/database/station/model/_NextStation.java
  src/main/java/com/swyp/mema/database/station/model/_Route.java
  src/main/java/com/swyp/mema/database/station/model/_Station.java
  src/main/java/com/swyp/mema/database/station/repository/_NextStationRepository.java
  src/main/java/com/swyp/mema/database/station/repository/_RouteRepository.java
  src/main/java/com/swyp/mema/database/station/repository/_StationRepository.java
  src/main/java/com/swyp/mema/database/station/util/AddrToCodeConverter.java
  src/main/java/com/swyp/mema/domain/user/converter/UserConverter.java
  src/main/java/com/swyp/mema/domain/user/service/CustomOAuthUserService.java
  src/main/java/com/swyp/mema/domain/user/service/JoinService.java
  src/main/java/com/swyp/mema/global/config/env/EnvConfig.java
  src/main/java/com/swyp/mema/global/config/security/SecurityConfig.java
Labels: ✨ Feature
