Repository swyp-mema/mema-server, pull requests merged in 2025-03, with the labels that each got.

#106 [#103] NaverAPI 맛집 추천 API 설정파일 추가
  src/main/resources/application.yml
Labels: ⚙️ Setting

#109 모든 지하철역 조회 API (/station/total) 속도 개선
  src/main/java/com/swyp/mema/database/station/dto/response/StationRes.java
  src/main/java/com/swyp/mema/database/station/repository/StationCustomRepository.java
  src/main/java/com/swyp/mema/database/station/repository/StationCustomRepositoryImpl.java
  src/main/java/com/swyp/mema/database/station/service/StationService.java
Labels: 🛠️ Refactor

#110 [#104] 중간역 조회 API 구현
  src/main/java/com/swyp/mema/database/station/controller/DBController.java
  src/main/java/com/swyp/mema/domain/midloc/service/MidLocService.java
  src/main/java/com/swyp/mema/domain/midlocation/dto/MidLocationDto.java
  src/main/java/com/swyp/mema/domain/midlocation/service/MidLocationService.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayInfo/SingleStationRes.java
  src/main/java/com/swyp/mema/domain/voteLocation/controller/LocationController.java
  src/main/java/com/swyp/mema/domain/voteLocation/converter/LocationConverter.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/response/MidLocationRes.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/response/MidLocationTotalRes.java
  src/main/java/com/swyp/mema/domain/voteLocation/service/LocationService.java
  src/test/java/com/swyp/mema/database/station/logic/subbuilder/StationDataBuilderServiceTest.java
  src/test/java/com/swyp/mema/domain/voteLocation/service/LocationServiceTest.java
Labels: ✨ Feature

#119 [#104] 중간역 계산 알고리즘 개선
  src/main/java/com/swyp/mema/domain/midlocation/service/MidLocationService.java
Labels: 🔧 Fix

#122 [#104] 중간역 알고리즘 개선
  src/main/java/com/swyp/mema/domain/midlocation/service/MidLocationService.java
Labels: 🔧 Fix

#123 [#121] 약속 API & 위치 생성 API DTO 네이밍 변경
  src/main/java/com/swyp/mema/database/openapi/location/converter/StationMasterConverter.java
  src/main/java/com/swyp/mema/database/station/logic/subbuilder/NextStationBuilderService.java
  src/main/java/com/swyp/mema/domain/meet/converter/MeetConverter.java
  src/main/java/com/swyp/mema/domain/meet/dto/response/SingleMeetRes.java
  src/main/java/com/swyp/mema/domain/station/dto/response/subwayInfo/SubwayInfoBasicRes.java
  src/main/java/com/swyp/mema/domain/station/model/Station.java
  src/main/java/com/swyp/mema/domain/station/service/StationServiceWithOpenAPI.java
  src/main/java/com/swyp/mema/domain/voteLocation/converter/LocationConverter.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/request/CreateLocationReq.java
Labels: 🔥 Front

#124 [#81] Facade 패턴을 이용하여 역할과 책임 분리
  src/main/java/com/swyp/mema/database/openapi/location/converter/StationMasterConverter.java
  src/main/java/com/swyp/mema/database/openapi/location/logic/StationMasterService.java
  src/main/java/com/swyp/mema/database/station/dto/response/nearSubway/NearSubwayBasicRes.java
  src/main/java/com/swyp/mema/database/station/dto/response/nearSubway/NearSubwayRes.java
  src/main/java/com/swyp/mema/database/station/dto/response/nearSubway/TotalNearSubwayRes.java
  src/main/java/com/swyp/mema/database/station/dto/response/subwayInfo/SingleStationRes.java
  src/main/java/com/swyp/mema/database/station/dto/response/subwayInfo/SubwayInfoBasicRes.java
  src/main/java/com/swyp/mema/database/station/dto/response/subwayInfo/TotalStationRes.java
  src/main/java/com/swyp/mema/database/station/dto/response/subwayTime/SubwayTimeBasicRes.java
  src/main/java/com/swyp/mema/database/station/dto/response/subwayTime/SubwayTimeRes.java
  src/main/java/com/swyp/mema/database/station/dto/response/subwayTime/TotalSubwayTimeRes.java
  src/main/java/com/swyp/mema/database/station/model/_Station.java
  src/main/java/com/swyp/mema/database/station/model/_TransferStation.java
  src/main/java/com/swyp/mema/domain/meet/service/MeetService.java
  src/main/java/com/swyp/mema/domain/meet/validator/MeetValidator.java
  src/main/java/com/swyp/mema/domain/meetMember/exception/UserAlreadyRegisteredException.java
  src/main/java/com/swyp/mema/domain/meetMember/service/MeetMemberService.java
  src/main/java/com/swyp/mema/domain/meetMember/validator/MeetMemberValidator.java
  src/main/java/com/swyp/mema/domain/midloc/service/MidLocService.java
  src/main/java/com/swyp/mema/domain/midloc/service/Stations.java
  src/main/java/com/swyp/mema/domain/midloc/service/structures/NextStation.java
  src/main/java/com/swyp/mema/domain/midloc/service/structures/StationInfo.java
  src/main/java/com/swyp/mema/domain/midloc/service/structures/TransferStation.java
  src/main/java/com/swyp/mema/domain/midloc/service/structures/UserInfo.java
  src/main/java/com/swyp/mema/domain/station/controller/StationController.java
  src/main/java/com/swyp/mema/domain/station/exception/StationNotFoundException.java
  src/main/java/com/swyp/mema/domain/station/model/Station.java
  src/main/java/com/swyp/mema/domain/station/repository/TmpStationRepository.java
  src/main/java/com/swyp/mema/domain/station/service/NearStationService.java
  src/main/java/com/swyp/mema/domain/station/service/StationServiceWithOpenAPI.java
  src/main/java/com/swyp/mema/domain/store/service/chatGPT/OpenAIWorker.java
  src/main/java/com/swyp/mema/domain/store/service/chatGPT/StoreServiceWithGPT.java
  src/main/java/com/swyp/mema/domain/user/exception/UserNotFoundException.java
  src/main/java/com/swyp/mema/domain/user/repository/UserRepository.java
  src/main/java/com/swyp/mema/domain/user/service/CustomOAuthUserService.java
  src/main/java/com/swyp/mema/domain/user/service/CustomUserDetailsService.java
  src/main/java/com/swyp/mema/domain/user/service/JoinService.java
  src/main/java/com/swyp/mema/domain/user/service/UserService.java
  src/main/java/com/swyp/mema/domain/user/validator/UserValidator.java
  src/main/java/com/swyp/mema/domain/voteLocation/controller/LocationController.java
  src/main/java/com/swyp/mema/domain/voteLocation/converter/LocationConverter.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/response/MidLocationRes.java
  src/main/java/com/swyp/mema/domain/voteLocation/dto/response/MidLocationTotalRes.java
  src/main/java/com/swyp/mema/domain/voteLocation/service/LocationService.java
  src/main/java/com/swyp/mema/domain/voteLocation/validator/LocationValidator.java
  src/main/java/com/swyp/mema/global/base/exception/ErrorCode.java
  src/main/java/com/swyp/mema/global/base/exception/ServiceException.java
  src/main/java/com/swyp/mema/global/config/security/SecurityConfig.java
  src/main/java/com/swyp/mema/global/validation/EntityValidator.java
  src/main/java/com/swyp/mema/global/validation/ValidationFacade.java
Labels: 🛠️ Refactor

#126 [#125] GitHub Actions로 Slack에 알림 발송하기
  .github/workflows/notify-pr-reivew.yml
  .github/workflows/remind-pr-review.yml
Labels: ✨ Feature
